export { default as halykImage } from './halyk.svg'
export { default as eurasianImage } from './eurasian.svg'
export { default as homeCreditImage } from './home-credit.svg'
export { default as freedomImage } from './freedom.svg'
export { default as forteImage } from './forte.png'
export { default as airbaImage } from './airba.png'
