export { default as cartImage } from './cart.svg'
export { default as deliveryImage } from './delivery.svg'
export { default as kaefImage } from './kaef.svg'
export { default as personImage } from './person.svg'
export { default as pointerImage } from './pointer.svg'
