export { default as comfortImage } from './comfort.png'
export { default as sweatersImage } from './sweaters.png'
export { default as glassesImage } from './glasses.png'
export { default as sneakersImage } from './sneakers.png'
export { default as sportImage } from './sport.png'
