export { default as male1Image } from './male1.webp'
export { default as male2Image } from './male2.webp'
export { default as male3Image } from './male3.webp'
export { default as male4Image } from './male4.webp'
export { default as male5Image } from './male5.jpeg'

export { default as female1Image } from './female1.webp'
export { default as female2Image } from './female2.webp'
export { default as female3Image } from './female3.webp'
export { default as female4Image } from './female4.webp'
export { default as female5Image } from './female5.webp'
